version: '3.1'

services:
  app:
    build: 
      context: .
      dockerfile: Development.Dockerfile
    ports:
      - "8000:8000"
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/LocalSlice
    stdin_open: true
    tty: true